name: GuildPlugin
version: '1.0-SNAPSHOT'
main: com.sironeko.guildplugin.GuildPlugin
api-version: '1.21'

commands:
  guild:
    description: ギルドの作成、参加
    usage: /<command> <create/join>
    aliases: [g]

permissions:
  master:
    description: "ギルドマスター権限"
    default: "op"

  R4:
    description: "幹部権限"
    default: "op"